. ./INITenvironnement.sh
#
echo "   tri_cipjj2.sh   "                                                                                                                                                                                                                                                                                                                                                                                                                                         
echo "-------------------"                                                                                                                                                                                                                                                                                                                                                                                                                                         
echo "TRI CIPDEC_HISTBAM APRES MAJ  " 
echo 
cp $FIC/CIPDEC_HISTBAM    $TMP/cipdec_fus_histb
#
echo "ENTREE TRI   : " `wc -l $TMP/cipdec_fus_histb`
#                                                                                                                                                                                                                                                                                                                                                                                                                                                        
mfsort SORT FIELDS \(1,45,CH,A\) USE $TMP/cipdec_fus_histb   ORG LS RECORD F,862 GIVE $FIC/cipdec_fus_histb ORG LS RECORD F,862                                                                                                                                                                                                                                                                                                      
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
echo                                                                                                                                                                                                 
echo "SORTIE       : " `wc -l $FIC/cipdec_fus_histb`                                                                                                                                                                                                                                                                                                                                                                                                                           
echo                                                                                                                                                                                                                                                                                                                                                                                                                                                               
