. ./INITenvironnement.sh
#
echo "   tri_cipjj1.sh   "                                                                                                                                                                                                                                                                                                                                                                                                                                         
echo "-------------------"                                                                                                                                                                                                                                                                                                                                                                                                                                         
echo "TRI ARCHIVAGE JJ ALIMENTATION CIP"                                                                                                                                                                                                                                                                                                                                                                                                           
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
mfsort SORT FIELDS \(9,19,CH,A,35,3,CH,A,49,1,CH,A,28,7,CH,A\) USE $TMP/HISTBAM_CIPJJ  ORG LS RECORD F,862 GIVE $FIC/CIPDEC_HISTBAM_JJ ORG LS RECORD F,862                                                                                                                                                                                                                                                                                                      
#                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
echo                                                                                                                                                                                                                                                                                                                                                                                                                                                               
echo "LUS    :" `wc -l $TMP/HISTBAM_CIPJJ `                                                                                                                                                                                                                                                                                                                                                                                                                
echo "ECR    :" `wc -l $FIC/CIPDEC_HISTBAM_JJ`                                                                                                                                                                                                                                                                                                                                                                                                                            
echo                                                                                                                                                                                                                                                                                                                                                                                                                                                               
